--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NoobyPE/CitizenTest
build-by-default: true
branches:
- patch-1
projects:
  CitizenTest:
    path: ""
    lint: 
       phpstan: false
    libs:
       - src: NoobyPE/Citizen/Citizen
         branch: master
         version: ^1.2.0-ALPHA
...
