name: CitizenTest
version: 1.1.0
main: iSrDxv\CitizenTest\Main
api: 5.0.0
commands:
  npc:
    description: Example Command
    usage: /npc
    permission: npc.cmd
    permission-message: "You do not have permission to use this example command!"
permissions:
  npc.cmd:
    default: true
    description: Send NPC
